const defaultsDeep = require('lodash.defaultsdeep');
var path = require('path');
var fs = require('fs');
var webpack = require('webpack');

// Plugins
var CopyWebpackPlugin = require('copy-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

// PostCss
var autoprefixer = require('autoprefixer');
var postcssVars = require('postcss-simple-vars');
var postcssImport = require('postcss-import');

const STATIC_PATH = process.env.STATIC_PATH || '/static';

const MONACO_DIR = path.resolve(__dirname, './node_modules/monaco-editor');
// Plain global css (no css-modules) shipped by third party widgets.
const XTERM_DIR = path.resolve(__dirname, './node_modules/@xterm');

const base = {
    mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
    devtool: 'cheap-module-source-map',
    devServer: {
        contentBase: [
            path.resolve(__dirname, 'build'),
            // Static snapshot of the external resources (devices / extensions),
            // generated by openblock-resource/script/build-static.js. Served
            // under the public path to mirror the production layout, where the
            // snapshot is copied into build/external-resources.
            path.resolve(__dirname, 'external-resources-static'),
            path.resolve(__dirname, 'external-resources-static')
        ],
        contentBasePublicPath: ['/', '/', '/scratch3/'],
        host: '0.0.0.0',
        port: process.env.PORT || 8601,
        disableHostCheck: true,
        // Forward the speech apis (tts / asr) to the kids-code-platform nginx
        // on the docker host, so the extensions work in development too.
        proxy: {
            '/api/v1/tts': {
                target: process.env.TTS_PROXY_TARGET || 'http://172.17.0.1',
                changeOrigin: true
            },
            '/api/v1/asr': {
                target: process.env.TTS_PROXY_TARGET || 'http://172.17.0.1',
                changeOrigin: true
            },
            '/api/v1/ai-chat': {
                target: process.env.TTS_PROXY_TARGET || 'http://172.17.0.1',
                changeOrigin: true
            }
        }
    },
    output: {
        library: 'GUI',
        filename: 'static/[name].js',
        chunkFilename: 'static/chunks/[name].js',
        publicPath: '/scratch3/'
    },
    resolve: {
        symlinks: false
    },
    module: {
        rules: [{
            test: /\.jsx?$/,
            loader: 'babel-loader',
            include: [
                path.resolve(__dirname, 'src'),
                /node_modules[\\/]scratch-[^\\/]+[\\/]src/,
                /node_modules[\\/]openblock-vm[\\/]src/,
                /node_modules[\\/]hxblock-l10n[\\/]src/,
                /node_modules[\\/]pify/,
                /node_modules[\\/]@vernier[\\/]godirect/,
                // xterm 5.x ships ES2021 syntax which the webpack 4 parser
                // can not read, run it through babel first.
                /node_modules[\\/]@xterm[\\/]/
            ],
            options: {
                // Explicitly disable babelrc so we don't catch various config
                // in much lower dependencies.
                babelrc: false,
                plugins: [
                    '@babel/plugin-syntax-dynamic-import',
                    '@babel/plugin-transform-async-to-generator',
                    '@babel/plugin-proposal-object-rest-spread',
                    ['react-intl', {
                        messagesDir: './translations/messages/'
                    }]],
                presets: ['@babel/preset-env', '@babel/preset-react']
            }
        },
        {
            test: /\.css$/,
            exclude: [MONACO_DIR, XTERM_DIR],
            use: [{
                loader: 'style-loader'
            }, {
                loader: 'css-loader',
                options: {
                    modules: true,
                    importLoaders: 1,
                    localIdentName: '[name]_[local]_[hash:base64:5]',
                    camelCase: true
                }
            }, {
                loader: 'postcss-loader',
                options: {
                    ident: 'postcss',
                    plugins: function () {
                        return [
                            postcssImport,
                            postcssVars,
                            autoprefixer
                        ];
                    }
                }
            }]
        },
        {
            test: /\.css$/,
            include: [MONACO_DIR, XTERM_DIR],
            use: ['style-loader', 'css-loader']
        }]
    },
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                include: /\.min\.js$/
            })
        ]
    },
    plugins: [
        new MonacoWebpackPlugin({
            languages: ['c', 'cpp', 'python', 'lua', 'javascript'],
            features: ['!gotoSymbol']
        })
    ]
};

if (!process.env.CI) {
    base.plugins.push(new webpack.ProgressPlugin());
}

module.exports = [
    // to run editor examples
    defaultsDeep({}, base, {
        entry: {
            'lib.min': ['react', 'react-dom'],
            'gui': './src/playground/index.jsx',
            'blocksonly': './src/playground/blocks-only.jsx',
            'compatibilitytesting': './src/playground/compatibility-testing.jsx',
            'player': './src/playground/player.jsx'
        },
        output: {
            path: path.resolve(__dirname, 'build'),
            filename: '[name].js'
        },
        module: {
            rules: base.module.rules.concat([
                {
                    test: /\.(svg|png|wav|gif|jpg|ttf)$/,
                    loader: 'file-loader',
                    options: {
                        outputPath: 'static/assets/'
                    }
                }
            ])
        },
        optimization: {
            splitChunks: {
                chunks: 'all',
                name: 'lib.min',
                cacheGroups: {
                    // esptool-js (browser firmware flasher, loaded through a
                    // dynamic import in openblock-vm) ships untranspiled
                    // ES2017 that UglifyJS cannot parse; keep it and its
                    // helpers out of the minified lib.min.js and in a lazy
                    // chunk that only loads when flashing firmware.
                    esptool: {
                        test: /[\\/]node_modules[\\/](esptool-js|pako|tslib|atob-lite)[\\/]/,
                        name: 'esptool-js',
                        chunks: 'async',
                        priority: 10
                    }
                }
            },
            runtimeChunk: {
                name: 'lib.min'
            }
        },
        plugins: base.plugins.concat([
            new webpack.DefinePlugin({
                'process.env.NODE_ENV': '"' + process.env.NODE_ENV + '"',
                'process.env.DEBUG': Boolean(process.env.DEBUG),
                'process.env.GA_ID': '"' + (process.env.GA_ID || 'UA-000000-01') + '"'
            }),
            new HtmlWebpackPlugin({
                chunks: ['lib.min', 'gui'],
                template: 'src/playground/index.ejs',
                title: 'OpenBlock',
                sentryConfig: process.env.SENTRY_CONFIG ? '"' + process.env.SENTRY_CONFIG + '"' : null
            }),
            new HtmlWebpackPlugin({
                chunks: ['lib.min', 'blocksonly'],
                template: 'src/playground/index.ejs',
                filename: 'blocks-only.html',
                title: 'OpenBlock GUI: Blocks Only Example'
            }),
            new HtmlWebpackPlugin({
                chunks: ['lib.min', 'compatibilitytesting'],
                template: 'src/playground/index.ejs',
                filename: 'compatibility-testing.html',
                title: 'OpenBlock GUI: Compatibility Testing'
            }),
            new HtmlWebpackPlugin({
                chunks: ['lib.min', 'player'],
                template: 'src/playground/index.ejs',
                filename: 'player.html',
                title: 'OpenBlock GUI: Player Example'
            }),
            new CopyWebpackPlugin([{
                from: 'static',
                to: 'static'
            }]),
            new CopyWebpackPlugin([{
                from: 'node_modules/hxblock-blocks/media',
                to: 'static/blocks-media'
            }]),
            new CopyWebpackPlugin([{
                from: 'extensions/**',
                to: 'static',
                context: 'src/examples'
            }]),
            new CopyWebpackPlugin([{
                from: 'extension-worker.{js,js.map}',
                context: (function () {
                    var web = path.resolve(__dirname, 'node_modules/openblock-vm/dist/web');
                    return fs.existsSync(web) ? web : path.resolve(__dirname, 'node_modules/openblock-vm/src/extension-support');
                })()
            }]),
            // Static snapshot of external devices/extensions so browser-direct
            // deployments do not need the local openblock-resource service.
            new CopyWebpackPlugin([{
                from: 'external-resources-static/external-resources',
                to: 'external-resources'
            }])
        ])
    })
].concat(
    process.env.NODE_ENV === 'production' || process.env.BUILD_MODE === 'dist' ? (
        // export as library
        defaultsDeep({}, base, {
            target: 'web',
            entry: {
                'openblock-gui': './src/index.js'
            },
            output: {
                libraryTarget: 'umd',
                path: path.resolve('dist'),
                publicPath: `${STATIC_PATH}/`
            },
            externals: {
                'react': 'react',
                'react-dom': 'react-dom'
            },
            module: {
                rules: base.module.rules.concat([
                    {
                        test: /\.(svg|png|wav|gif|jpg|ttf)$/,
                        loader: 'file-loader',
                        options: {
                            outputPath: 'static/assets/',
                            publicPath: `${STATIC_PATH}/assets/`
                        }
                    }
                ])
            },
            plugins: base.plugins.concat([
                new CopyWebpackPlugin([{
                    from: 'node_modules/hxblock-blocks/media',
                    to: 'static/blocks-media'
                }]),
                new CopyWebpackPlugin([{
                    from: 'extension-worker.{js,js.map}',
                    context: (function () {
                        var web = path.resolve(__dirname, 'node_modules/openblock-vm/dist/web');
                        return fs.existsSync(web) ? web : path.resolve(__dirname, 'node_modules/openblock-vm/src/extension-support');
                    })()
                }]),
                // Include library JSON files for scratch-desktop to use for downloading
                new CopyWebpackPlugin([{
                    from: 'src/lib/libraries/*.json',
                    to: 'libraries',
                    flatten: true
                }])
            ])
        })) : []
);
